### ISSUE TITLE
Rejected shares

### ISSUE THREAD

**Issue by Majorbafe** [KotoDevelopers/cpuminer-yescrypt#6]
I'm trying to use your miner to mine for zpool and I get 100% rejected shares from it.
I looked into the command prompt and all the found shares are rejected.

What's up with this?

**Comment by 345-chan** [comment]
zpool does not seem to correspond to Koto.
This official miner software is made exclusively for Koto.
Please check the corresponding currency.
https://zpool.ca/coins
